### ISSUE TITLE
What happened with TINYINT mysql type?

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#289]
Hi!

In 3.5 all works well, but in 3.7 or 3.8:
```
exception 'Kwf_Exception' with message 'Column "pos" must not be of type TINYINT in table "employeeStaffRoles"' in C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Model\Db.php:63
Stack trace:
#0 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Model\Db.php(1421): Kwf_Model_Db->getColumnType('pos')
#1 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Model\Db\Row.php(45): Kwf_Model_Db->convertValueType('pos', '1')
#2 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Field\MultiFields.php(216): Kwf_Model_Db_Row->__get('pos')
#3 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Field_MultiFields->load(Object(Row_Employee), Array)
#4 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#5 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#6 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#7 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#8 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#9 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Controller\Action\Auto\Form.php(97): Kwf_Form_Container_Abstract->load(NULL)
#10 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonLoadAction()
#11 C:\OpenServer\domains\aviashelf1\library\zend\1.10.7\Zend\Controller\Dispatcher\Standard.php(295): Kwf_Controller_Action->dispatch('jsonLoadAction')
#12 C:\OpenServer\domains\aviashelf1\library\zend\1.10.7\Zend\Controller\Front.php(953): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#13 C:\OpenServer\domains\aviashelf1\kwf-lib\Kwf\Controller\Front.php(142): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#14 C:\OpenServer\domains\aviashelf1\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#15 {main}
```

It's a basic type. What's wrong with it?

I had to switch all data types from TINYINT to SMALLINT but in standard KWF tables you still using the TINYINT. I don't understand =))

**Comment by nsams** [comment]
TINYINT is boolean a in Kwf_Model.

pos must not be TINTYINT as it would just be true/false.
