### ISSUE TITLE
Can't update DB schema from 3.5 to 3.8 (much pain bug)

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#291]
Hi!

I am still facing the consequences of improper schemes (many bugs) and the inability to go with standard command.

If I use "php bootstrap.php update":
```
c:\OpenServer\domains\aviashelf>php bootstrap.php update
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'portal2.kwf_update' doesn't exist' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:228
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Pdo->_execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE kwf_upda...', 'a:8:{i:0;s:16:"...')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Update\Helper.php(206): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE kwf_upda...', 'a:8:{i:0;s:16:"...')
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\Web\UpdateController.php(53): Kwf_Util_Update_Helper::getExecutedUpdatesNames()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_Web_UpdateController->indexAction()
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#10 C:\OpenServer\domains\aviashelf\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#11 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'portal2.kwf_update' doesn't exist, query was: UPDATE kwf_update SET data=?' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:235
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(323): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE kwf_upda...', 'a:8:{i:0;s:16:"...')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Update\Helper.php(206): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE kwf_upda...', 'a:8:{i:0;s:16:"...')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\Web\UpdateController.php(53): Kwf_Util_Update_Helper::getExecutedUpdatesNames()
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_Web_UpdateController->indexAction()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\aviashelf\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#10 {main}
```

If I add this table by hands from kwf-app-demo (without data) and do same update command:
```
c:\OpenServer\domains\aviashelf>php bootstrap.php update
No update revision found, assuming up-to-date
```

What next? What data can I put into 'kwf_update' to update schema from 3.5 to 3.8 correctly? Now I copy tables and fields to my DB in case of errors.

p.s.
I looked which tables (kwc and kwf) I have:
* kwc_fulltext_meta
* kwf_log_duplicate
* kwf_pools
* kwf_redirects
* kwf_uploads
* kwf_users
* kwf_user_messages
* kwf_welcome
* kwf_sessions **(now added by hands to work with memcache)**

That's all. But in kwf-app-demo are more of them, including those which are due to errors.

**Comment by nsams** [comment]
`php bootstrap.php update` executes all update scripts found in kwf + app. It also remembers the already executed update scripts to make sure they don't get executed again. (that would result in errors when creating a eg. table again)

In 3.5 the list of executed update scripts was saved in a file in the app: `update`.

In 3.8 the list of executed update scripts is saved in database in `kwf_update`.

When you have a db dump from 3.5 (without kwf_update) you NEED the update file. Else you get the message `No update revision found, assuming up-to-date` and no update script at all is executed.

Do you have the `update` file? Does it help if you copy it?

**Comment by Sogl** [comment]
I haven't `update` file in all project. 

>When you have a db dump from 3.5 (without kwf_update) you NEED the update file. Else you get the message No update revision found, assuming up-to-date and no update script at all is executed.

I don't think so. As I described higher, it looks into DB and if not find `kwf_update` table - error. 
Message `No update revision found, assuming up-to-date` shows only if I add this table by hands (without data because I don't know what the data is).

What can I do now?

**Comment by nsams** [comment]
I just checked, kwf 3.5 already uses kwf_update, it was introduced with kwf 3.2.

So you need kwf_update table, if you don't have that table update scripts can't be executed correctly.

**Comment by nsams** [comment]
If you really don't have this table you could create it and fake it's contents - to force /all/ update scripts getting executed again. You'll get many errors though - you can ignore them.

But that is more a brute force method of updating...

**Comment by Sogl** [comment]
Interesting... but do you have data from 3.5 db? 
I think all update scripts create many unuseful tables and fields.

**Comment by nsams** [comment]
that's the contents of a 3.4 app:
https://gist.github.com/nsams/cc1112ec480702377312

try inserting that into the database and execute update

**Comment by Sogl** [comment]
The system could not find the path specified:
```
c:\OpenServer\domains\aviashelf>php bootstrap.php update
[ 1/10] clearing simpleCache... OK (2ms)
[ 2/10] clearing model......... OK (16ms)
[ 3/10] clearing simple........ OK (61ms)
[ 4/10] clearing twig.......... OK (1ms)
[ 5/10] clearing zend.......... OK (1ms)
[ 6/10] clearing config........ OK (1ms)
[ 7/10] clearing setup......... OK (1ms)
[ 8/10] clearing assets........ OK (7ms)
Looking for update-scripts from revision 1 to 9999999... found 4

 25% [#####----------------] Kwf_Update_38013                                  Системе не удается найти указанный путь.
 50% [###########----------] Kwf_Update_38014                                  Системе не удается найти указанный путь.

Error:
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'autologin'

 75% [################-----] Kwf_Update_38015                                  Системе не удается найти указанный путь.

Error:
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activate_token'

100% [#####################] Kwf_Update_38016
[ 1/10] clearing simpleCache... OK (1ms)
[ 2/10] clearing model......... OK (0ms)
[ 3/10] clearing simple........ OK (14ms)
[ 4/10] clearing twig.......... OK (1ms)
[ 5/10] clearing zend.......... OK (1ms)
[ 6/10] clearing config........ OK (1ms)
[ 7/10] clearing setup......... OK (1ms)
[ 8/10] clearing assets........ OK (1ms)
[9/10] refreshing config...... OK (8ms)
[10/10] refreshing setup....... OK (62ms)


update finished


================
2 update script(s) failed:
Kwf_Update_38014:
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'autologin'

Kwf_Update_38015:
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'activate_token'
```

Despite errors, new table 'kwf_logs' adds to DB. 

Tables now:
```
kwc_fulltext_meta
kwc_log_duplicate
kwf_logs (by script)
kwf_pools
kwf_redirects
kwf_sessions (by hands)
kwf_sessions
kwf_update (by hands)
kwf_uploads
kwf_users
kwf_user_messages
kwf_welcome
```

Is it all?

**Comment by nsams** [comment]
looks correct.

the errors you can ignore as you created the columns already manually.

and in future the update will work as it should...
