### ISSUE TITLE
ERROR: Can't find dependency 'KwfTinyMce'

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#316]
Hi!

Today I tried to update KWF by 'composer update' and if fails:
```
c:\OpenServer\domains\aviashelf>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mouf/nodejs-installer (v1.0.0)
    Downloading: 100%

  - Updating koala-framework/composer-extra-assets (v1.0.1 => v1.1.0)
    Checking out 4860eb4c7041824559962a0fc1a3b139fc501444

  - Installing psr/log (1.0.0)
    Downloading: 100%

  - Installing monolog/monolog (1.13.1)
    Downloading: 100%

  - Installing symfony/finder (v2.6.5)
    Downloading: 100%

  - Installing symfony/event-dispatcher (v2.6.5)
    Downloading: 100%

  - Installing koala-framework/file-watcher (dev-master 16ca00a)
    Cloning 16ca00a1b7cdac053a1760b45a5385d31b1bc278

  - Installing symfony/console (v2.6.5)
    Downloading: 100%

  - Updating koala-framework/kwf-modernizr 3.8.x-dev (0e62ee2 => 51f4f70)
    Checking out 51f4f707413a74d371866e50b275f7317e0ac8d9

  - Updating koala-framework/koala-framework 3.8.x-dev (c9cdd71 => b1959d9)
    Checking out b1959d98fadb06f46d2e555106bfe2f3d41b394b

monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\aviashelf/vendor/koala-framework/kwf-modernizr'...

installing npm dependencies in 'C:\OpenServer\domains\aviashelf/vendor/koala-framework/koala-framework'...
amdlc@0.1.5 node_modules\amdlc
тФФтФАтФА glob@5.0.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)

installing bower dependencies...
bower tinymce#4.1.9         not-cached git://github.com/tinymce/tinymce.git#4.1.9
bower tinymce#4.1.9            resolve git://github.com/tinymce/tinymce.git#4.1.9
bower tinymce#4.1.9           download https://github.com/tinymce/tinymce/archive/4.1.9.tar.gz
bower tinymce#4.1.9           progress received 0.6MB
bower tinymce#4.1.9           progress received 0.6MB
bower tinymce#4.1.9           progress received 0.7MB
bower tinymce#4.1.9            extract archive.tar.gz
bower tinymce#4.1.9       invalid-meta tinymce is missing "main" entry in bower.json
bower tinymce#4.1.9       invalid-meta tinymce is missing "ignore" entry in bower.json
bower tinymce#4.1.9           resolved git://github.com/tinymce/tinymce.git#4.1.9
bower tinymce#4.1.9            install tinymce#4.1.9

tinymce#4.1.9 vendor\bower_components\tinymce

c:\OpenServer\domains\aviashelf>php bootstrap.php clear-cache
[ 1/10] clearing simpleCache... OK (11ms)
[ 2/10] clearing model......... OK (15ms)
[ 3/10] clearing simple........ OK (70ms)
[ 4/10] clearing twig.......... OK (1ms)
[ 5/10] clearing zend.......... OK (1ms)
[ 6/10] clearing config........ OK (1ms)
[ 7/10] clearing setup......... OK (0ms)
[ 8/10] clearing assets........ OK (10ms)
[9/10] refreshing config...... OK (28ms)
[10/10] refreshing setup....... OK (148ms)

c:\OpenServer\domains\aviashelf>php bootstrap.php build
[ 1/3] building trl...... OK (56ms)
[ 2/3] building events... OK (92ms)
[ 3/3] building assets...
calculating dependencies...
 75% [################-----] Maintenance js                                    exception 'Kwf_Exception' with message 'Can't find dependency 'KwfTinyMce'' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php:37
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('ExtHtmlEditIniD...')
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(46): Kwf_Assets_ProviderList_Abstract->findDependency('ExtHtmlEditIniD...')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('ExtHtmlEdit')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('ExtHtmlEdit')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('KwfWelcomeIniDe...')
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(46): Kwf_Assets_ProviderList_Abstract->findDependency('KwfWelcomeIniDe...')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('KwfWelcome')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('KwfWelcome')
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('KwfCoreIniDep')
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(46): Kwf_Assets_ProviderList_Abstract->findDependency('KwfCoreIniDep')
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('KwfCore')
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('KwfCore')
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('MaintenanceIniD...')
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(46): Kwf_Assets_ProviderList_Abstract->findDependency('MaintenanceIniD...')
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('Maintenance')
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(28): Kwf_Assets_ProviderList_Abstract->findDependency('Maintenance')
#16 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(81): Kwf_Assets_Package->getDependency()
#17 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(75): Kwf_Assets_Package->_getFilteredUniqueDependencies('text/javascript')
#18 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(140): Kwf_Assets_Package->getFilteredUniqueDependencies('text/javascript')
#19 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#20 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#21 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#22 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#23 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#24 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#25 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#26 C:\OpenServer\domains\aviashelf\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#27 {main} [ERROR] (1057ms)
```

**Comment by Sogl** [comment]
How to fix? I can't work with my app now.

**Comment by nsams** [comment]
should work now, please test

**Comment by Sogl** [comment]
No.

Next error:
```
c:\OpenServer\domains\aviashelf>php bootstrap.php build
[ 1/3] building trl...... OK (126ms)
[ 2/3] building events... OK (181ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 37% [########-------------] tinymce                                           "." не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
exception 'Kwf_Exception' with message 'tinymce build failed: ' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\TinyMce\BuildDependency.php:26
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(168): Kwf_Assets_TinyMce_BuildDependency->warmupCaches()
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#9 {main} [ERROR] (6840ms)
```

**Comment by nsams** [comment]
Fixed.

Tested with kwf-app-demo on windows 8

**Comment by Sogl** [comment]
Finally works! =)

**Comment by nsams** [comment]
Ok, sorry for breaking windows builds from time to time :/

**Comment by Sogl** [comment]
Last update broke clear-cache-watcher in Windows:
```
c:\OpenServer\domains\aviashelf>php bootstrap.php clear-cache-watcher
```

Nothing happenes.

**Comment by nsams** [comment]
I can not reproduce on windows with kwf-app-demo.

Please open a new issue for that.

**Comment by Sogl** [comment]
Today after composer update:
```
c:\OpenServer\domains\aviashelf>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
ИНФОРМАЦИЯ: не удается найти файлы по заданным шаблонам.
ИНФОРМАЦИЯ: не удается найти файлы по заданным шаблонам.

installing npm dependencies in 'C:\OpenServer\domains\aviashelf/vendor/koala-framework/kwf-modernizr'...
"install" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.



  [RuntimeException]
  npm install failed



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

**Comment by nsams** [comment]
please run with `LC_ALL=C composer update` to get a error message I can read....

**Comment by nsams** [comment]
Oh and please create a new issue for every issue you you get - so we don't loose overview....
