### ISSUE TITLE
Error in mixing controllers in JS

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#342]
Hi!

If I use controllers from different folders I see error:
```
{
  "error": "Not found",
  "exception": [
    "exception 'Kwf_Exception_NotFound' with message 'Not found' in \/var\/www\/puls\/vendor\/koala-framework
\/koala-framework\/Kwf\/Controller\/Action\/Error\/ErrorController.php:15",
    "Stack trace:",
    "#0 \/var\/www\/puls\/vendor\/koala-framework\/koala-framework\/Kwf\/Controller\/Action.php(33):
 Kwf_Controller_Action_Error_ErrorController->errorAction()",
    "#1 \/var\/www\/puls\/vendor\/koala-framework\/zendframework1\/library\/Zend\/Controller\/Dispatcher
\/Standard.php(308): Kwf_Controller_Action->dispatch('errorAction')",
    "#2 \/var\/www\/puls\/vendor\/koala-framework\/zendframework1\/library\/Zend\/Controller\/Front.php
(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http
))",
    "#3 \/var\/www\/puls\/vendor\/koala-framework\/koala-framework\/Kwf\/Controller\/Front.php(140):
 Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http
))",
    "#4 \/var\/www\/puls\/bootstrap.php(20): Kwf_Controller_Front->dispatch()",
    "#5 {main}"
  ],
  "success": false
}
```

View with error:
https://gist.github.com/Sogl/c00e6510edef8a107220

Part with error:
```javascript
var flighttracks = new Kwf.Auto.GridPanel({
              controllerUrl   : '/fligthplans/flighttracks',
              region          : 'center',
              title           : trl('Ответственные')
        });
                             
        var planerstates = new Kwf.Auto.GridPanel({
              controllerUrl   : '/fligthplans/planerstates',
              region          : 'center',
              title           : trl('Состояния ВС')
        });
```

**Comment by Sogl** [comment]
Found a mistake in controller name. Sorry =)
Closed.
