### ISSUE TITLE
3.9: build fails if non-static trl is used in getSettings 'build/trl/kwfde was not created in build'

### ISSUE THREAD

**Issue by nsams** [koala-framework/koala-framework#352]
[ 1/4] building componentSettings... exception 'Kwf_Exception' with message 'build/trl/kwfde was not created in build' in /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Trl.php:405                                                                                                                                                                          
    Stack trace:                                                                                                                                                                           
    #0 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Trl.php(428): Kwf_Trl->_loadTrlElements('kwf', 'de', false)                                                          
    #1 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Trl.php(335): Kwf_Trl->_findElement('full width', 'kwf', '', NULL)                                                   
    #2 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Trl.php(315): Kwf_Trl->_trlc('', 'full width', Array, 'kwf', NULL)                                                   
    #3 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Trl.php(71): Kwf_Trl->trlKwf('full width', Array)                                                                    
    #4 /var/www/dreieichen/vendor/koala-framework/kwc-parallax/Kwc/Parallax/ParallaxImage/Image/Component.php(10): trlKwf('full width')                                                    
    #5 [internal function]: Kwc_Parallax_ParallaxImage_Image_Component::getSettings(NULL)                                                                                                  
    #6 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(100): call_user_func(Array, NULL)                                                             
    #7 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(261): Kwf_Component_Settings::_loadCacheSettings('Kwc_Parallax_Pa...')                        
    #8 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Abstract.php(35): Kwf_Component_Settings::getSetting('Kwc_Parallax_Pa...', 'generators')                   
    #9 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(481): Kwf_Component_Abstract::getSetting('Kwc_Parallax_Pa...', 'generators')                  
    #10 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Kwc_Parallax_Pa...')         
    #11 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Kwc_Parallax_Pa...')         
    #12 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Theme_Backgroun...')         
    #13 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Kwc_Paragraphs_...')         
    #14 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Kwc_Root_Catego...')         
    #15 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(507): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Root_Master_Com...')         
    #16 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(455): Kwf_Component_Settings::_getChildComponentClasses(Array, 'Root_Component')             
    #17 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Component/Settings.php(417): Kwf_Component_Settings::getComponentClasses()                                          
    #18 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/ComponentSettings.php(14): Kwf_Component_Settings::_getSettingsCached()                            
    #19 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/Abstract.php(15): Kwf_Util_Build_Types_ComponentSettings->_build(Array)                            
    #20 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)                                                     
    #21 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Cli/BuildController.php(35): Kwf_Util_Build->build(Array)                                         
    #22 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()                                 
    #23 /var/www/dreieichen/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')                     
    #24 /var/www/dreieichen/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))                                                                                                                                                 
    #25 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))                                                                                                                                                                       
    #26 /var/www/dreieichen/bootstrap.php(9): Kwf_Controller_Front->dispatch()
    #27 /var/www/library/kwfscripts/vps.php(641): include('/var/www/dreiei...')
    #28 {main} [ERROR] (172ms)
    [ 2/4] building trl................. exception 'Kwf_Exception' with message 'In getSettings-method only static version of trl is allowed /var/www/dreieichen/vendor/koala-framework/kwc-parallax/Kwc/Parallax/ParallaxImage/Image/Component.php:10' in /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/Trl.php:50
    Stack trace:
    #0 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/Abstract.php(15): Kwf_Util_Build_Types_Trl->_build(Array)
    #1 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Util/Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
    #2 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Cli/BuildController.php(35): Kwf_Util_Build->build(Array)
    #3 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
    #4 /var/www/dreieichen/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
    #5 /var/www/dreieichen/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
    #6 /var/www/dreieichen/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
    #7 /var/www/dreieichen/bootstrap.php(9): Kwf_Controller_Front->dispatch()
    #8 /var/www/library/kwfscripts/vps.php(641): include('/var/www/dreiei...')
    #9 {main} [ERROR] (35ms)

**Comment by nsams** [comment]
fixed in 3.9
