### ISSUE TITLE
using _getParam in Table_Row class

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#362]
Hi!

My view contains has left and right regions used by two controllers.
How to get left panel id in right panel table_row class?

Usually I use this code:
```php
$this->_getParam('workId'); 
```

But it works on table class and not works in row class.

**Comment by nsams** [comment]
_getParam only works in Controllers - you can access all parameters passed in the AJAX request.

If you need additional parameters you have to add them in javascript (eg. use applyBaseParams on the auto grid panel)

**Comment by Sogl** [comment]
>If you need additional parameters you have to add them in javascript (eg. use applyBaseParams on the auto grid panel)

Can I use it in model row class? 
I calculate some virtual rows from other tables and need ID from left region/panel for that.

**Comment by nsams** [comment]
No, the row class doesn't have the request object.

If you need to calculate something in the row you can define a method with the required parameters and pass those from the controller.

The starting point is *always* the controller and only that has access to the parameters. (that's how MVC works)

**Comment by Sogl** [comment]
How to create additional virtual column in controller (with calculations from other model instances)?

**Comment by Sogl** [comment]
Let me explain.

I define virtual field in controller (uses also for grouping):
```
$this->_columns->add(new Kwf_Grid_Column('Group', trl('Группа'), 100));
```

Calculations into model row:
```
public function __get($name) {
        if ($name === 'Group') {

        //some calculations with other tables

        return $calculated_value;

        } else
        return parent::__get($name);
    }
```

And I need `_getParam('workId');` into this calculations... 
How to transfer this model code to the controller where I can use `_getParam`?

**Comment by nsams** [comment]
You can do that by using a custom Data class:

    $this->_columns->add(new Kwf_Grid_Column('Group', trl('Группа'), 100))
        ->setData(new FooData($this->_getParam('workId')));
        
    class FooData extends Kwf_Data_Abstract
    {
        private $_workId;
        public function __construct($workId)
        {
            $this->_workId = $workId;
        }
        public function load($row, array $info)
        {
            return $row->Group;
        }
    }

**Comment by Sogl** [comment]
Doesn't work.

Model:
```php
<?php
class Flightaccesses extends Kwf_Model_Db
{
    protected $_table = 'flightAccesses';
    protected $_default = array(
        'setsCount' => 0
    );
    protected $_referenceMap = array(
       'Employee' => array(
             'column'           => 'employeeId',
             'refModelClass'     => 'Employees',
        ),
       'File' => array(
            'column'           => 'file_id',
            'refModelClass'     => 'Kwf_Uploads_Model'
        )
    );
}
```

Exception:
```php
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:228
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#17 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#18 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null, query was: INSERT INTO `flightAccesses` (`docId`, `docName`, `employeeId`, `employeeName`, `accessId`, `accessName`, `wsTypeId`, `wsTypeName`, `comment`, `accessTypeId`, `accessTypeName`, `accessDate`, `accessEndDate`, `docNumber`, `speciality`, `department`, `flightsCount`, `setsCount`, `file_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:235
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#17 {main}
```
