### ISSUE TITLE
Memcache CLIENT_ERROR bad command line format

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#372]
Hi!

Today I found this error:
```
exception 'ErrorException' with message 'MemcachePool::set(): Server localhost (tcp 11211, udp 0) failed with: CLIENT_ERROR bad command line format
 (6)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php:77
Stack trace:
#0 [internal function]: Kwf_Debug::handleError(8, 'MemcachePool::s...', 'C:\\OpenServer\\d...', 77, Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php(77): MemcachePool->set('C:\\OpenServer\\d...', 1434955094, 0, -24889687)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media.php(42): Kwf_Media_MemoryCache->load('mtime-Kwf_Form_...')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\ImageViewer.php(28): Kwf_Media::getUrl('Kwf_Form_Field_...', 69, 'original', Object(Kwf_Uploads_Row))
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Field_ImageViewer->load(Object(Row_Employee), Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(97): Kwf_Form_Container_Abstract->load(NULL)
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonLoadAction()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonLoadAction')
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#16 {main}
```

I think this is problem with uploads component. This file doesn't exists on my local machine (uploads folder) and this causes an error.

**Comment by nsams** [comment]
Probably the key is too long, could you try the following patch in koala-framework:

    diff --git a/Kwf/Cache/Simple.php b/Kwf/Cache/Simple.php
    index 5cfbce4..33bc36f 100644
    --- a/Kwf/Cache/Simple.php
    +++ b/Kwf/Cache/Simple.php
    @@ -230,7 +230,7 @@ class Kwf_Cache_Simple
        {
            static $ret;
            if (!isset($ret)) {
    -            $ret = getcwd().'-'.Kwf_Setup::getConfigSection().'-';
    +            $ret = substr(md5(getcwd().'-'.Kwf_Setup::getConfigSection()), 0, 8).'-';
            }
            return $ret;
        }

If that works we can apply it. Which branch do you currently use?

**Comment by Sogl** [comment]
Nothing changed.

Code with error:
```php
$tab->fields->add(new Kwf_Form_Field_ImageViewer('picture_id', trl('Фото'), 'Picture'));

$tab->fields->add(new Kwf_Form_Field_File('Picture', trlKwf('File')))
->setShowPreview(false)
->setAllowOnlyImages(true);
```

If I change it to this - works fine:
```php
$tab->fields->add(new Kwf_Form_Field_File('Picture', trlKwf('File')))
->setShowPreview(true)
->setAllowOnlyImages(true);
```

**Comment by nsams** [comment]
please post the exception you get now.

**Comment by Sogl** [comment]
Solved as I wrote above.

**Comment by nsams** [comment]
?

how did you solve it?

**Comment by Sogl** [comment]
https://github.com/koala-framework/koala-framework/issues/372#issuecomment-118205954

**Comment by nsams** [comment]
well, that is just a workaround...

**Comment by Sogl** [comment]
Error still exists with old code... and with your changes in KWF:
https://github.com/koala-framework/koala-framework/issues/372#issuecomment-117022876

**Comment by nsams** [comment]
ok, please post the exception you get with my change

**Comment by Sogl** [comment]
Exception:
```
exception 'ErrorException' with message 'MemcachePool::set(): Server localhost (tcp 11211, udp 0) failed with: CLIENT_ERROR bad command line format
 (6)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php:77
Stack trace:
#0 [internal function]: Kwf_Debug::handleError(8, 'MemcachePool::s...', 'C:\\OpenServer\\d...', 77, Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php(77): MemcachePool->set('e52e8ad9--media...', 1434955094, 0, -24889687)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media.php(42): Kwf_Media_MemoryCache->load('mtime-Kwf_Form_...')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\ImageViewer.php(28): Kwf_Media::getUrl('Kwf_Form_Field_...', 69, 'original', Object(Kwf_Uploads_Row))
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Field_ImageViewer->load(Object(Row_Employee), Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(97): Kwf_Form_Container_Abstract->load(NULL)
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonLoadAction()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonLoadAction')
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#16 {main}
```

**Comment by nsams** [comment]
Interesting.

Please also try the following patch:

    diff --git a/Kwf/Media/MemoryCache.php b/Kwf/Media/MemoryCache.php
    index e0ee8d1..7a77aa9 100644
    --- a/Kwf/Media/MemoryCache.php
    +++ b/Kwf/Media/MemoryCache.php
    @@ -72,11 +72,13 @@ class Kwf_Media_MemoryCache
                    //first level empty, refill from second level contents
                    $metaDatas = $this->_getSecondLevelCache()->getMetadatas($id);
                    $ttl = $metaDatas['expire'] ? $metaDatas['expire']-$metaDatas['mtime'] : 0;
    -                if ($be == 'memcache') {
    -                    $flags = is_int($ret) ? null : MEMCACHE_COMPRESSED;
    -                    Kwf_Cache_Simple::getMemcache()->set($prefix.$id, $ret, $flags, $ttl);
    -                } else {
    -                    Kwf_Cache_Simple::add('media-'.$id, $ret, $ttl);
    +                if ($ttl > 0) {
    +                    if ($be == 'memcache') {
    +                        $flags = is_int($ret) ? null : MEMCACHE_COMPRESSED;
    +                        Kwf_Cache_Simple::getMemcache()->set($prefix.$id, $ret, $flags, $ttl);
    +                    } else {
    +                        Kwf_Cache_Simple::add('media-'.$id, $ret, $ttl);
    +                    }
                    }
                }
            }

**Comment by Sogl** [comment]
Exception:
```
exception 'ErrorException' with message 'MemcachePool::set(): Server localhost (tcp 11211, udp 0) failed with: CLIENT_ERROR bad command line format
 (6)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php:78
Stack trace:
#0 [internal function]: Kwf_Debug::handleError(8, 'MemcachePool::s...', 'C:\\OpenServer\\d...', 78, Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media\MemoryCache.php(78): MemcachePool->set('e52e8ad9--media...', 1434955094, 0, -24889687)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Media.php(42): Kwf_Media_MemoryCache->load('mtime-Kwf_Form_...')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\ImageViewer.php(28): Kwf_Media::getUrl('Kwf_Form_Field_...', 69, 'original', Object(Kwf_Uploads_Row))
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Field_ImageViewer->load(Object(Row_Employee), Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\Abstract.php(156): Kwf_Form_Container_Abstract->load(Object(Row_Employee), Array)
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Container\Abstract.php(161): Kwf_Form_Field_Abstract->load(Object(Row_Employee), Array)
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(97): Kwf_Form_Container_Abstract->load(NULL)
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonLoadAction()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonLoadAction')
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#16 {main}
```

**Comment by nsams** [comment]
I'm not sure you applied the patch correctly.

Please do a git diff in vendor/koala-framework/koala-framework and post the output

**Comment by Sogl** [comment]
>Please do a git diff in vendor/koala-framework/koala-framework and post the output
Output is very big =(

**Comment by nsams** [comment]
why that? You should not have too many changes there!

post it using eg. http://pastebin.com/

**Comment by Sogl** [comment]
I see all another files in output, but not my changes. Can't post it, because it's so big.

**Comment by nsams** [comment]
Sorry, I can't help you with that. You should not have *any* changes in vendor.

**Comment by nsams** [comment]
... did you manage to get the diff or apply the diff correclty?
