### ISSUE TITLE
Problem with ORM dependencies (select in select)

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#379]
Hi!

I'm trying to use JOIN with other table.
My php code:
```php
$s = new Kwf_Model_Select();
$s->where(new Kwf_Model_Select_Expr_Sql('TypeName = \'Вертолёт\' AND suTypeName = \'Много\''));
$flightresultsSelect = $flightresultsModel->select()->where(new Kwf_Model_Select_Expr_Sql('ownerId = ' . $employee->id
                                                                                   .' AND flightDate <= \'' . $endDateMonth1->format('Y-m-d')
                                                                                   .'\' AND typeName = \'Налет общий\'
                                                                                   AND flightTime <> \'00:00:00\''))
                                                                                   ->where(new Kwf_Model_Select_Expr_Child_Contains('Wsmodels', $s));
$flightresultsRows = $flightresultsModel->getRows($flightresultsSelect);
```

Result sql query:
```sql
SELECT `flightResults`.* FROM `flightResults` WHERE ((ownerId = 51 AND flightDate <= '2015-06-30' AND typeName = 'Налет общий' AND flightTime <> '00:00:00')) 
AND (flightResults.id IN (SELECT `wsModels`.`id` FROM `wsModels` WHERE ((TypeName = 'Вертолёт' AND suTypeName = 'Много'))))
```

But I want to use `flightResults.planeId` in query, not `flightResults.id`.
How to do that? 

My models.
Flightresults.php:
```php
<?php
class Flightresults extends Kwf_Model_Db
{
    protected $_table = 'flightResults';
    protected $_referenceMap = array(
        'Plane' => array(
            'column'           => 'planeId',
            'refModelClass'     => 'Wsmodels',
        )
    );

    protected $_dependentModels = array(
        'Wsmodels' => 'Wsmodels'
    );
}
```

Wsmodels.php:
```php
<?php
class Wsmodels extends Kwf_Model_Db
{
    protected $_table = 'wsModels';
    protected $_toStringField = 'Name';

    protected $_referenceMap = array(
        'Flightresult' => array(
            'column'           => 'id',
            'refModelClass'     => 'Flightresults',
        )
    );
}
```

**Comment by nsams** [comment]
The column for the Flightresult reference is set to 'id' but it should be the referencing column.

**Comment by Sogl** [comment]
>The column for the Flightresult reference is set to 'id' but it should be the referencing column.

I tried this, but it's `Wsmodels` table column:
```
exception 'Kwf_Exception' with message 'Can't find field 'planeId' in model 'Wsmodels' (Table 'wsModels')' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php:172
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(654): Kwf_Model_Db->_formatField('planeId', NULL)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(355): Kwf_Model_Db->_createDbSelectExpression(Object(Kwf_Model_Select_Expr_Child_Contains), Object(Kwf_Db_Table_Select))
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(279): Kwf_Model_Db->_applySelect(Object(Kwf_Db_Table_Select), Object(Kwf_Model_Select))
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(933): Kwf_Model_Db->createDbSelect(Object(Kwf_Model_Select))
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(879): Kwf_Model_Db->_getDbSelect(Object(Kwf_Model_Select), NULL, NULL, NULL)
#5 C:\OpenServer\domains\aviashelf\controllers\Reporter.php(2195): Kwf_Model_Db->getRows(Object(Kwf_Model_Select))
#6 C:\OpenServer\domains\aviashelf\controllers\Exceluploads\ExceluploadsController.php(97): Reporter->exportENLdata(Object(PHPExcel), Object(PHPExcel_Worksheet), '105', Object(Zend_ProgressBar))
#7 C:\OpenServer\domains\aviashelf\controllers\Exceluploads\ExceluploadsController.php(155): Exceluploads_ExceluploadsController->_fillTheXlsFile(Object(PHPExcel), Object(PHPExcel_Worksheet), 'exxon', '105')
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Exceluploads_ExceluploadsController->jsonXlsAction()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonXlsAction')
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#12 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#13 {main}
```

I can change `Wsmodels` column by this, but how to change for `Flightresults`?

**Comment by Sogl** [comment]
Maybe I can use only manual query in this case?

**Comment by nsams** [comment]
It should be `flightresultId`, no?

and yes, you can always execute manual queries - however this should also be possible using models.

**Comment by Sogl** [comment]
>It should be flightresultId, no?
Nope.
It should be `planeId`.

**Comment by nsams** [comment]
well, if you have a reference to `'refModelClass'     => 'Flightresults',`, why should that be planeId?

please post the db structure you have, and the changed models.

**Comment by Sogl** [comment]
Flightresults:
![screenshot_19](https://cloud.githubusercontent.com/assets/7556290/8718244/32ddfdb2-2be6-11e5-96b9-3ea1c23aea62.jpg)

Flightresults.php (full):
```php
<?php
class Flightresults extends Kwf_Model_Db
{
    protected $_table = 'flightResults';
    protected $_referenceMap = array(
        'Plane' => array(
            'column'           => 'planeId',
            'refModelClass'     => 'Wsmodels',
        ),
       'Type' => array(
            'column'           => 'typeId',
            'refModelClass'     => 'Linkdata',
        ),
       'Owner' => array(
             'column'           => 'ownerId',
             'refModelClass'     => 'Employees',
        ),
       'Flight' => array(
              'column'           => 'flightId',
              'refModelClass'     => 'Flights',
        )
    );

    protected $_dependentModels = array(
        'Wsmodels' => 'Wsmodels'
    );
}
```

Wsmodels:
![screenshot_20](https://cloud.githubusercontent.com/assets/7556290/8718247/39823fca-2be6-11e5-9171-687ed2e56f20.jpg)

Wsmodels.php (full):
```php
<?php
class Wsmodels extends Kwf_Model_Db
{
    protected $_table = 'wsModels';
    protected $_toStringField = 'Name';

    protected $_referenceMap = array(
        'Flightresult' => array(
            'column'           => 'id',
            'refModelClass'     => 'Flightresults',
        )
    );
}
```

Sql query I have:
```sql
SELECT `flightResults`.* FROM `flightResults` WHERE ((ownerId = 51 AND flightDate <= '2015-06-30' AND typeName = 'Налет общий' AND flightTime <> '00:00:00')) 
AND (flightResults.id IN (SELECT `wsModels`.`id` FROM `wsModels` WHERE ((TypeName = 'Вертолёт' AND suTypeName = 'Много'))))
```

Sql query I need:
```sql
SELECT `flightResults`.* FROM `flightResults` WHERE ((ownerId = 51 AND flightDate <= '2015-06-30' AND typeName = 'Налет общий' AND flightTime <> '00:00:00')) 
AND (flightResults.planeId IN (SELECT `wsModels`.`id` FROM `wsModels` WHERE ((TypeName = 'Вертолёт' AND suTypeName = 'Много'))))
```

**Comment by nsams** [comment]
How is flightResults associated with wsModels? Please post the relevant foreign keys.

**Comment by Sogl** [comment]
>How is flightResults associated with wsModels? Please post the relevant foreign keys.

`planeId` in flightResults is FK for wsModels.

**Comment by nsams** [comment]
Ok, this is how your models should look like:

    class Wsmodels extends Kwf_Model_Db
    {
        protected $_table = 'wsModels';
        protected $_toStringField = 'Name';

        protected $_dependentModels = array(
            'Flightresults' => 'Flightresults'
        );
    }

    class Flightresults extends Kwf_Model_Db
    {
        protected $_table = 'flightResults';
        protected $_referenceMap = array(
            'Plane' => array(
                'column'           => 'planeId',
                'refModelClass'     => 'Wsmodels',
            ),
            'Type' => array(
                'column'           => 'typeId',
                'refModelClass'     => 'Linkdata',
            ),
            'Owner' => array(
                'column'           => 'ownerId',
                'refModelClass'     => 'Employees',
            ),
            'Flight' => array(
                'column'           => 'flightId',
                'refModelClass'     => 'Flights',
            )
        );
    }

Wsmodels is a parent model of Flightresults, so you don't have to use Chid_Contains

**Comment by Sogl** [comment]
There is no SQL relation between the tables. Does it matter?

>Wsmodels is a parent model of Flightresults, so you don't have to use Chid_Contains

How to construct query with Koala ORM in this situation?

**Comment by Sogl** [comment]
Niko?

**Comment by Sogl** [comment]
@nsams 
Now did in this way:
```php
$flightresultsModel = Kwf_Model_Abstract::getInstance('Flightresults');
$flightresultsSelect = $flightresultsModel->select()
    ->whereEquals('ownerId', $employeeId)
    ->where('flightDate <= ?', $endDate->format('Y-m-d'))
    ->whereEquals('typeName', $type)
    ->where('flightTime <> ?', '00:00:00')
    ->where('flightResults.planeId IN (SELECT wsModels.id FROM wsModels WHERE suTypeName = ?)', 'Много');
$flightresults = $flightresultsModel->getRows($flightresultsSelect);
```

But how to build JOIN query using KWF models? I reviewed all the docs and source code and couldn't find how to build such query.

**Comment by Sogl** [comment]
Done :laughing:
My problem was in using `Kwf_Model_Select_Expr_Child_Contains`, but I had to use `Kwf_Model_Select_Expr_Parent_Contains`. 

```php
$modelsSelect = new Kwf_Model_Select();
$modelsSelect->where(new Kwf_Model_Select_Expr_Sql("suTypeName = 'Много'"));

$flightresultsModel = Kwf_Model_Abstract::getInstance('Flightresults');
$flightresultsSelect = $flightresultsModel->select()
    ->whereEquals('ownerId', $employeeId)
    ->where('flightDate <= ?', $endDate->format('Y-m-d'))
    ->whereEquals('typeName', $type)
    ->where('flightTime <> ?', '00:00:00')
    ->where(new Kwf_Model_Select_Expr_Parent_Contains('Plane', $modelsSelect));
$flightresults = $flightresultsModel->getRows($flightresultsSelect);
```

One question is still open. How to use `JOIN` types instead of `SELECT IN (SELECT ...)`?

**Comment by nsams** [comment]
JOIN isn't used by Kwf_Model_Db, mainly because Subqueries are much easier to implement. Usually both do the same.

If you want hand-crafted, optimized sql queries with JOIN you'll have to write those manually.
