### ISSUE TITLE
Defalut MySQL column value bug

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#382]
Hi!

If in MySQL column of type `INT` you use `not null` and `0` as default value, after saving form without selecting in dropdown I got an exception:
```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:228
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#17 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#18 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null, query was: INSERT INTO `flightAccesses` (`docId`, `docName`, `employeeId`, `employeeName`, `accessId`, `accessName`, `wsTypeId`, `wsTypeName`, `comment`, `accessTypeId`, `accessTypeName`, `accessDate`, `accessEndDate`, `docNumber`, `speciality`, `department`, `flightsCount`, `setsCount`, `file_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:235
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#17 {main}
```

But value must be `0` without errors.

**Comment by Sogl** [comment]
Also found if column is `nullable` and default value is `NULL`, after save with `not selected` in dropdown... becomes `0` in DB.

**Comment by nsams** [comment]
Set default values like that:

    class Foo extends Kwf_Model_Db
    {
        protected $_table = 'app_foo';
        protected $_default = array(
            'xxx' => 0
        );
    }

**Comment by Sogl** [comment]
Doesn't work.

Model:
```php
<?php
class Flightaccesses extends Kwf_Model_Db
{
    protected $_table = 'flightAccesses';
    protected $_default = array(
        'setsCount' => 0
    );
    protected $_referenceMap = array(
       'Employee' => array(
             'column'           => 'employeeId',
             'refModelClass'     => 'Employees',
        ),
       'File' => array(
            'column'           => 'file_id',
            'refModelClass'     => 'Kwf_Uploads_Model'
        )
    );
}
```

Exception:
```php
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:228
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#17 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#18 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'setsCount' cannot be null, query was: INSERT INTO `flightAccesses` (`docId`, `docName`, `employeeId`, `employeeName`, `accessId`, `accessName`, `wsTypeId`, `wsTypeName`, `comment`, `accessTypeId`, `accessTypeName`, `accessDate`, `accessEndDate`, `docNumber`, `speciality`, `department`, `flightsCount`, `setsCount`, `file_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement\Pdo.php:235
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `fl...', Array)
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `fl...', Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('flightAccesses', Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Db\Table\Row\Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Db\Table\Row\Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php(333): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form.php(130): Kwf_Model_Row_Abstract->save()
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Form.php(176): Kwf_Form->save(NULL, Array)
#12 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#13 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#14 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#15 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#16 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#17 {main}
```
