### ISSUE TITLE
PreLogin not working with custom username and password

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#455]
Hi!

I'm from this article:
http://www.koala-framework.org/documentation/kwf_general_features/config/prelogin

My `config.local.ini`:
```
preLogin = true
preLogin.username = admin
preLogin.password = admin
```

After that change I see error:
```
exception 'Zend_Config_Exception' with message 'Cannot create sub-key for 'preLogin' as key already exists' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php:294
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php(261): Zend_Config_Ini->_processKey(Array, 'preLogin.userna...', 'admin')
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php(153): Zend_Config_Ini->_processSection(Array, 'production')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(220): Zend_Config_Ini->__construct('./config.local....', 'production')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(119): Kwf_Config_Web->_mergeWebConfig('production', '.')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(42): Kwf_Config_Web->__construct('production')
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config.php(40): Kwf_Config_Web::getInstance()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Setup.php(189): Kwf_Config::getValue('server.baseUrl')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Setup.php(39): Kwf_Setup::getBaseUrl()
#8 C:\OpenServer\domains\aviashelf\bootstrap.php(10): Kwf_Setup::setUp()
#9 {main}


Error happened while handling exception:exception 'Zend_Config_Exception' with message 'Cannot create sub-key for 'preLogin' as key already exists' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php:294
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php(261): Zend_Config_Ini->_processKey(Array, 'preLogin.userna...', 'admin')
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php(153): Zend_Config_Ini->_processSection(Array, 'production')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(220): Zend_Config_Ini->__construct('./config.local....', 'production')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(119): Kwf_Config_Web->_mergeWebConfig('production', '.')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(42): Kwf_Config_Web->__construct('production')
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config.php(40): Kwf_Config_Web::getInstance()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Component\Data\Root.php(67): Kwf_Config::getValue('kwc.rootCompone...')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Exception\Abstract.php(67): Kwf_Component_Data_Root::getComponentClass()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Debug.php(190): Kwf_Exception_Abstract->render()
#9 [internal function]: Kwf_Debug::handleException(Object(Zend_Config_Exception))
#10 {main}
```

Works only with `test/test` for username and password.

p.s. Cache cleared.

**Comment by fraxachun** [comment]
This should work:

preLogin = true
preLoginUser = admin
preLoginPassword = admin

**Comment by Sogl** [comment]
Works now. Please fix it on documentation page.
