### ISSUE TITLE
Error when adding edit button to rows

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#458]
Hi!

First time I see this error:
```
exception 'Kwf_Exception' with message 'Can't find field 'edit' in model 'FlightNew' (Table 'flightNew')' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php:172
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(946): Kwf_Model_Db->_formatField('edit', Object(Kwf_Db_Table_Select))
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(879): Kwf_Model_Db->_getDbSelect(Object(Kwf_Model_Select), NULL, NULL, NULL)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(288): Kwf_Model_Db->getRows(Object(Kwf_Model_Select))
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(360): Kwf_Controller_Action_Auto_Grid->_fetchData(Array, 100, NULL)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Grid->jsonDataAction()
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonDataAction')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#9 {main}
```

My code:
```
$this->_columns->add(new Kwf_Grid_Column_Button('edit'));
```

All other controllers works fine, but this works only without edit button. Why?

**Comment by Sogl** [comment]
In docs:
http://www.koala-framework.org/documentation/kwf_general_features/autoform_autogrid/autogrid_editdialog

Finally works with this line:
```
$this->_columns->add(new Kwf_Grid_Column_Button());
```

But in other controllers works with this line:
```
$this->_columns->add(new Kwf_Grid_Column_Button('edit'));
```

Strange and illogical :confused:

**Comment by nsams** [comment]
This error happens when the button is the first column and the grid automatically tries to order by the first one.

either:

- specify default order manually
- move a column that actually exists in the model to the first position
