### ISSUE TITLE
Can't create new user in MySQL strict mode (bug)

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#503]
Hi!

I use MySQL 5.7 with strict mode (default).
From `my.cnf`:
```
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

I can't create user in KWF with this mode:
```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'logins' cannot be null' in /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `kw...', Array)
#4 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `kw...', Array)
#5 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('kwf_users', Array)
#6 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Row/Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#7 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Row/Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#8 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Db/Table/Row/Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#9 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Db/Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#10 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Proxy/Row.php(109): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#11 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Row/Abstract.php(333): Kwf_Model_Proxy_Row->_saveWithoutResetDirty()
#12 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/User/EditRow.php(139): Kwf_Model_Row_Abstract->save()
#13 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Form.php(130): Kwf_User_EditRow->save()
#14 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Auto/Form.php(176): Kwf_Form->save(NULL, Array)
#15 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#16 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#17 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#18 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#19 /var/www/puls/bootstrap.php(20): Kwf_Controller_Front->dispatch()
#20 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'logins' cannot be null, query was: INSERT INTO `kwf_users` (`role`, `language`, `email`, `password`, `password_salt`, `gender`, `title`, `firstname`, `lastname`, `created`, `deleted`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' in /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `kw...', Array)
#3 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `kw...', Array)
#4 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('kwf_users', Array)
#5 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Row/Abstract.php(467): Zend_Db_Table_Abstract->insert(Array)
#6 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Db/Table/Row/Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#7 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Db/Table/Row/Abstract.php(106): Zend_Db_Table_Row_Abstract->save()
#8 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Db/Row.php(89): Kwf_Db_Table_Row_Abstract->save()
#9 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Proxy/Row.php(109): Kwf_Model_Db_Row->_saveWithoutResetDirty()
#10 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Model/Row/Abstract.php(333): Kwf_Model_Proxy_Row->_saveWithoutResetDirty()
#11 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/User/EditRow.php(139): Kwf_Model_Row_Abstract->save()
#12 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Form.php(130): Kwf_User_EditRow->save()
#13 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Auto/Form.php(176): Kwf_Form->save(NULL, Array)
#14 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(33): Kwf_Controller_Action_Auto_Form->jsonSaveAction()
#15 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('jsonSaveAction')
#16 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#17 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#18 /var/www/puls/bootstrap.php(20): Kwf_Controller_Front->dispatch()
#19 {main}
```
Column `logins` in MySQL `IS NOT NULL`.

KWF 3.8. 
Same with 3.9.

**Comment by Sogl** [comment]
I checked with the same `sql_mode` in MySQL 5.5 and it works. Mybe related with another 5.7 difference.

Workaround for me `DEFAULT 0`.

**Comment by Sogl** [comment]
Also I saw same type of errors in update scrips...

**Comment by nsams** [comment]
Well, those also should be fixed. Either report the errors or - even better - send us patches :D
