### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#528]
Hi!

Today I created a new controller in the same way as usual and got an error: 
```
exception 'ErrorException' with message 'Illegal offset type in isset or empty' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php:61
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(61): Kwf_Debug::handleError(2, 'Illegal offset ...', 'C:\\OpenServer\\d...', 61, Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(182): Kwf_Model_Db->getColumnType(Array)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(21): Kwf_Controller_Action_Auto_Grid->preDispatch()
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#6 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#7 {main}
```

How to fix?

**Comment by nsams** [comment]
what's in that line? Which kwf version do you use?

**Comment by Sogl** [comment]
>what's in that line?

```php
public function getColumnType($col)
    {
        $info = $this->getTable()->info();
        if (isset($info['metadata'][$col])) {  //LINE 61
            $type = $this->_getTypeFromDbType($info['metadata'][$col]['DATA_TYPE']); 
            if ($col == 'pos' && $type == self::TYPE_BOOLEAN) {
                throw new Kwf_Exception('Column "pos" must not be of type TINYINT in table "' . $info['name'] . '"');
            }
            return $type;
        }
        return parent::getColumnType($col);
    }
```

>Which kwf version do you use?
KWF 3.8

**Comment by nsams** [comment]
It seems primaryKey is an array:

    #1 Kwf\Controller\Action\Auto\Grid.php(182): Kwf_Model_Db->getColumnType(Array)

And that is not supported by getColumnType. Make sure you use a single column as primary key.

**Comment by Sogl** [comment]
>It seems primaryKey is an array

No array data type in whole table:
![image](https://cloud.githubusercontent.com/assets/7556290/16248338/4cf144f8-385a-11e6-9d03-7d3106b5d7a1.png)

**Comment by nsams** [comment]
You have two columns as primary key defined (id and chat_id), thats why the variable in php primaryKey is an array. Don't do that, just use a single column as primary key.

**Comment by Sogl** [comment]
Main problem is that table used by external library that working in same DB with KWF PDO object. So I can't change column type because it may bring some problems with this library.

Any thoughts?

**Comment by nsams** [comment]
Ok, is Id column unique?

**Comment by Sogl** [comment]
No. No default value also in both columns.

**Comment by nsams** [comment]
You must have a single unique column for AutoGrid to work correctly.

If you don't have that currently add an additional auto_increment column - you can keep the existing columns and also read it's values.

**Comment by Sogl** [comment]
>You must have a single unique column for AutoGrid to work correctly.

Inuque index not helps me. Same error.
![image](https://cloud.githubusercontent.com/assets/7556290/16575213/29bc3e7a-42d2-11e6-966f-c6a6bc17eb3a.png)



>If you don't have that currently add an additional auto_increment column - you can keep the existing columns and also read it's values.

I can't. It adds only with `No default`, but not with `AUTO_INCREMENT`.
![image](https://cloud.githubusercontent.com/assets/7556290/16575044/a189c2a8-42d0-11e6-8690-263b69dfa11e.png)

Related library issue:
https://github.com/akalongman/php-telegram-bot/issues/184
