### ISSUE TITLE
How to set custom field order

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#534]
Hi!

I want to set order like this:

``` php
protected $_defaultOrder = "time < '06:00'";
```

But it not working because KWF looks it as field name:

```
exception 'Kwf_Exception' with message 'Can't find field 'time < '06:00'' in model 'FlightMessages' (Table 'flightMessages')' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php:172
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(946): Kwf_Model_Db->_formatField('time < '06:00'', Object(Kwf_Db_Table_Select))
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db.php(879): Kwf_Model_Db->_getDbSelect(Object(Kwf_Model_Select), NULL, NULL, NULL)
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(288): Kwf_Model_Db->getRows(Object(Kwf_Model_Select))
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(360): Kwf_Controller_Action_Auto_Grid->_fetchData(Array, 100, NULL)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Grid->jsonDataAction()
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonDataAction')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#9 {main}
```

How to do this?

**Comment by Sogl** [comment]
@nsams Can you help with this thing?

**Comment by nsams** [comment]
you can define an expression in your model (see http://docs.koala-framework.org/kwf-general-features/models/stored-expressions/)

    protected function _init()
    {
        $this->_exprs['time_before_6'] = new Kwf_Model_Select_Expr_Sql('time < '06:00'');
    }

and use that expression in the controller

    protected $_defaultOrder = "time_before_6";

**Comment by Sogl** [comment]
Thx, it works.
