### ISSUE TITLE
Invalid Source Map during build

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#566]
Hi!

Sometimes with build command on Linux I see this error:
```
25% [######----------------] kwf/Kwf_js/Auto/Filter/Text.js                    exception 'Exception' with message 'Invalid Source Map' in /var/www/puls/vendor/koala-framework/sourcemaps/Kwf/SourceMaps/SourceMap.php:29
Stack trace:
#0 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Assets/Dependency/Filter/UglifyJs.php(31): Kwf_SourceMaps_SourceMap->__construct('{"sources":["kw...', 'Kwf.Auto.Filter...')
#1 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Assets/Dependency/File/Js.php(43): Kwf_Assets_Dependency_Filter_UglifyJs::build('/tmp/kwf-uglify...', 'kwf/Kwf_js/Auto...')
#2 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/Assets.php(166): Kwf_Assets_Dependency_File_Js->warmupCaches()
#3 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Util/Build/Types/Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#4 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Util/Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#5 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Cli/BuildController.php(35): Kwf_Util_Build->build(Array)
#6 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#7 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#8 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#9 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(136): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#10 /var/www/puls/bootstrap.php(22): Kwf_Controller_Front->dispatch()
#11 {main} [ERROR]
```

Build repeat or delete `kwf-uglifyjs` folder helps me.

**Comment by nsams** [comment]
There seems to be an invalid sourcemap file generated by uglifyjs

Does it alsway happen for the same file?

**Comment by Sogl** [comment]
Hard to say, it showed to me 2 times in one day.
Need to investigate more.

I will write again if an error occurs.
